services:
  tv_kabel_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
        SECRET_KEY: ${SECRET_KEY}
        NODE_ENV: ${NODE_ENV}
        IMAGEKIT_PUBLIC_KEY: ${IMAGEKIT_PUBLIC_KEY}
        IMAGEKIT_PRIVATE_KEY: ${IMAGEKIT_PRIVATE_KEY}
        IMAGEKIT_URL_ENDPOINT: ${IMAGEKIT_URL_ENDPOINT}
        ADMIN_USERNAME: ${ADMIN_USERNAME}
        ADMIN_PASSWORD: ${ADMIN_PASSWORD}

    container_name: tv_kabel_app
    restart: unless-stopped
    ports:
      - "8000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - NODE_ENV=production
      - IMAGEKIT_PUBLIC_KEY=${IMAGEKIT_PUBLIC_KEY}
      - IMAGEKIT_PRIVATE_KEY=${IMAGEKIT_PRIVATE_KEY}
      - IMAGEKIT_URL_ENDPOINT=${IMAGEKIT_URL_ENDPOINT}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    env_file:
      - .env
