import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer } from "./_components/footer";
import { CustomerHeader } from "./_components/header";
import { getCustomerNotificationCount } from "@/actions/customer-notification";
import { getSettings } from "@/actions/settings";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [notificationCount, setting] = await Promise.all([
    getCustomerNotificationCount(),
    getSettings(),
  ]);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CustomerHeader setting={setting!} notifications={notificationCount} />
        {children}
        <Footer setting={setting!} />
      </body>
    </html>
  );
}
